name: michael o music
favicon: null
layout_spectrum: 0.02640121290460229
typography_spectrum: 0.37344173062592745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6635054289363325
  lightness: 0.20169842359609902
  saturation: 0.6786868018098176
  rhythmicContrast: 0.5835468606092036
purpose: []
